### ISSUE TITLE
Please add TITLE BLOCK

### ISSUE THREAD

**Issue by papilinou** [circuitdiagram/components#102]
As in other drawing software a Title Block could be interesting.

**Comment by papilinou** [comment]
this is my Title block component design.
Please give me your feeling and remarks before i set a pull request.

![Capture title block-1](https://user-images.githubusercontent.com/3898168/98576813-5bd75700-22bb-11eb-8761-a337acef1cfe.JPG)
![Capture title block-2](https://user-images.githubusercontent.com/3898168/98576836-64c82880-22bb-11eb-85b2-17fb2ecff2a4.JPG)

**Comment by SamuelFisher** [comment]
This repository is purely for electronic component symbols currently, so I'm afraid this would not be accepted as a pull request at this time. Please feel free to continue using it in Circuit Diagram Desktop though.
