### ISSUE TITLE
Phototransistor

### ISSUE THREAD

**Issue by M0Dark1** [circuitdiagram/components#11]
Does anyone know how to add a phototransistor to the app?

**Comment by SamuelFisher** [comment]
There is a compatibility issue to resolve first because I have split the transistor and mosfet into separate components, but this is what it will look like:

![image](https://user-images.githubusercontent.com/5303088/47266384-7fd96b80-d52d-11e8-8658-636d3de5f43c.png)

**Comment by SamuelFisher** [comment]
[Phototransistor](https://www.circuit-diagram.org/components/22bbfc5a-29d9-455f-b0bf-c582e7c71de9) now available.
