### ISSUE TITLE
Resistor Value rounds off to whole number during Download

### ISSUE THREAD

**Issue by syddo** [circuitdiagram/components#118]
I am having a problem with the resistor value of 27.5k ohms being rounded off to 28k ohms whenever I download my schematic. (Download -> PNG).

How do we work around this?

**Comment by SamuelFisher** [comment]
Hi, please could you post a link to an example of this happening?

It works as expected in this circuit: https://crcit.net/c/223acdc6e884487dbe5798840e4b90a3
