### ISSUE TITLE
Adding icons to the desktop version

### ISSUE THREAD

**Issue by portrf** [circuitdiagram/components#119]
I have downloaded various components in addition to those included with the desktop program, but none of them have an icon in the left-hand toolbar. There is just a blank black space, though the name appears underneath. Is it possible to get icons here? They are usually just a negative (white on black) of the component symbol.
Thanks

**Comment by SamuelFisher** [comment]
Hi, these downloaded components do not include icons like the default components do.

However, it is possible to manually add icons for them. If you would like to do this there are instructions here:

https://www.circuit-diagram.org/docs/components/finishing

Thanks
