### ISSUE TITLE
Adding icons to the Desktop version

### ISSUE THREAD

**Issue by portrf** [circuitdiagram/components#126]
The documentation contains instuctions for adding icons at  https://www.circuit-diagram.org/docs/components/finishing
The example is:

	> circuit-diagram-cli component resistor.xml --resources resistor_32.png ./icon.png  -o resistor.cdcom

	To use a different icon for each configuration, multiple resources can be specified. You can see the list of expected icon names when 		compiling a component with verbose logging enabled:

	> circuit-diagram-cli component resistor.xml -o resistor.cdcom --verbose
	...
	Icon resistor_32.png not found.
	Icon resistor_64.png not found.
	Icon resistor_resistor_iec_32.png not found.
	Icon resistor_resistor_iec_64.png not found.
	...

I have tried and failed with this.
For example with the signal generator component I created a white on transparent black icon called sgicon.png and used the full path names in CLI:

c:\Program Files\Circuit Diagram\CLI>
circuit-diagram-cli component c:\files\electronics-data\signal-generator.xml --resources signal-generator_32.png ./c:\files\electronics-data\sgicon.png -o c:\files\electronics-data\signal-generator.cdcom

A cdcom file is created OK but with messages saying icon not found. Various attempts give the same result.
I am not clear about the "--resources" statement, should the full path name to the expected file be here (I have tried this)?
Is the ./ command OK? There is no help file covering the --resources statement.

PS the --verbose qualifier gives an error message.

**Comment by SamuelFisher** [comment]
Hi, to answer your query about using the full path, you can use the full path if you like. To do so, you would specify that argument like this:

```
--resources signal-generator-32.png c:\files\electronics-data\sgicon.png
```

The `./` character means "relative to the current directory where you are running this command". You do not want to use this if you are specifying a full path.

Secondly, on the issue you mentioned with `--verbose`, are you using the newest version of the CLI? It would be worth downloading the newest version from here if you are not:

https://www.circuit-diagram.org/downloads

You can check which version you are using by running the command below (shown with the output it produces):

```
> circuit-diagram-cli --version
4.0.2-pre.3+f9267be29e
```

As you can see, at the time of writing the newest version is `4.0.2-pre.3`.

Please let me know if you still have a problem with this on the newest version.
