### ISSUE TITLE
Servo component

### ISSUE THREAD

**Issue by psharma04** [circuitdiagram/components#13]
It'd be useful to have a dedicated servo component

**Comment by SamuelFisher** [comment]
Is there a standard symbol for this? If so, please could you provide a link for reference?

**Comment by psharma04** [comment]
I don't think there's a standard symbol, however a Google Search brings up the following:
[Servo-Symbol-150x96.jpg](http://douglaslee.com/wp-content/uploads/2014/07/Servo-symbol-150x96.jpg)

**Comment by SamuelFisher** [comment]
Added in 1ec67d5 - see [Servo Motor](https://www.circuit-diagram.org/components/47f5c83d-a23b-484a-a1f3-2ea0d6c98e0b).
