### ISSUE TITLE
[Request] Oscilloscope needed

### ISSUE THREAD

**Issue by SansBold** [circuitdiagram/components#134]
Hey! I mainly use _Circuits Diagram_ to draw circuits I build in my physics class. I couldn't find anything that resembles an oscilloscope in the existing components, so I would be really glad if anyone could add this instrument to the list.
Thank you in advance.

This is the circuit symbol used to represent the oscilloscope:
![Oscilloscope-Circuit-Symbol](https://user-images.githubusercontent.com/82956842/115571185-0ddd6b00-a2bf-11eb-9ecc-33ea0171e05d.jpg)

**Comment by SamuelFisher** [comment]
This has been added:

https://www.circuit-diagram.org/components/7958ad29-1bde-4996-a819-6849d8d406f6
