### ISSUE TITLE
Arduino Nano, Leonardo, Mega/Mega 2560 component and shields

### ISSUE THREAD

**Issue by psharma04** [circuitdiagram/components#14]
Lack of Arduino components???

**Comment by SamuelFisher** [comment]
[Arduino Nano v3](https://www.circuit-diagram.org/components/12b926b7-a05a-46b8-aa02-86e1265f2420) added in 1786815:

![image](https://user-images.githubusercontent.com/5303088/50401931-4a016f00-078a-11e9-9d6c-ee15ddcfee50.png)

**Comment by ahmed240** [comment]
Need Mega 2560 / Due

**Comment by Corsaka** [comment]
@ahmed240 use the "Integrated Circuit 2" component and make it yourself in Circuit Diagram

**Comment by SamuelFisher** [comment]
[Arduino Mega 2560](https://www.circuit-diagram.org/components/06f95e06-7a49-4e7a-abc3-9c6818ca5f70) has been added.

**Comment by SamuelFisher** [comment]
[Arduino Leonardo](https://www.circuit-diagram.org/components/13b733d9-bb0d-40fd-97fb-ab1b6b194680) has been added.
