### ISSUE TITLE
Hall Effect Sensor Component

### ISSUE THREAD

**Issue by 13rac1** [circuitdiagram/components#174]
We need a [Hall Effect Sensor](https://en.wikipedia.org/wiki/Hall_effect_sensor) Component
![Common_Hall_Sensor_Symbol](https://user-images.githubusercontent.com/195061/157695783-32184df1-81fa-4bf2-add5-49430c5b3c55.png)

**Comment by SamuelFisher** [comment]
Added in https://github.com/circuitdiagram/components/pull/230:

https://www.circuit-diagram.org/components/6b6cd12d-9fd5-4fef-81b6-6a3732133252
