### ISSUE TITLE
Communication bus component

### ISSUE THREAD

**Issue by VoxelPrismatic** [circuitdiagram/components#175]
Basically this combines a bunch of wires into a single thick one, and labels the incoming and outgoing wires so you know which one is which.
Kind of like this:
![image](https://user-images.githubusercontent.com/45671764/157782581-fd06aea2-43db-4a96-b1c5-8760719b2ce7.png)

The purpose of this component is to reduce visual clutter, like this:
![image](https://user-images.githubusercontent.com/45671764/157782781-d5eb283f-d7d8-46bc-9026-2f62b4a69feb.png)

It would be much nicer to have one thick wire in the diagram that transports all 8 wires to drive the display instead of 8 individual wires and eventually running out of space.

**Comment by SamuelFisher** [comment]
This has been added in https://github.com/circuitdiagram/components/pull/253.

Please see: https://www.circuit-diagram.org/components/cf17d038-e185-4912-a80f-2e326c0dac9d
