### ISSUE TITLE
ESP 8266 and Variants

### ISSUE THREAD

**Issue by Schnosch** [circuitdiagram/components#203]

**Comment by ryanlaycock** [comment]
Specifically ESP32 would be great 🎉

**Comment by radius611** [comment]
Would Love to see esp12-E/F and ESP32

**Comment by SamuelFisher** [comment]
ESP32 was added in https://github.com/circuitdiagram/components/pull/228:

https://www.circuit-diagram.org/components/c893311f-5562-483d-9b5f-33647b77cfdb

**Comment by Gabsang-Lee-Lab** [comment]
Still would really appreciate ESP8266

**Comment by metawops** [comment]
Me too. A "pure" ESP8266 or some ESP8266 dev board, like the Wemos D1 mini would be nice. 👍👍

**Comment by SamuelFisher** [comment]
ESP8266 is now available:

https://www.circuit-diagram.org/components/v/extended/8b909330-633e-44b9-8207-8281814cd128/0.3.1

Some further ESP32-XX components can be found here:

https://github.com/circuitdiagram/ext-components/tree/master/kicad/mcu_espressif
