### ISSUE TITLE
multiwire bus

### ISSUE THREAD

**Issue by rimminggrandma** [circuitdiagram/components#252]
How do I get this component? I saw @everlastingwonder said something about it like 2 years ago, but I don't see the component on the site. Unless if I missed it

![131070452-f45a0894-3eb9-4f9f-9a28-07b9754c6ceb](https://github.com/circuitdiagram/components/assets/146609207/70cae604-6430-46f8-876e-24947e3881ae)

**Comment by SamuelFisher** [comment]
This has been added in https://github.com/circuitdiagram/components/pull/253.

Please see: https://www.circuit-diagram.org/components/cf17d038-e185-4912-a80f-2e326c0dac9d
