### ISSUE TITLE
Stepper Motors

### ISSUE THREAD

**Issue by fregac** [circuitdiagram/components#289]
Trying to add steppers to a few schematics I am making, the existing component does not seem to be properly designed.  I don't know why there is an input for supply voltage, and "Input 1-4" doesn't do anything to tell you which coil those go to.  While there are various options I think at the least a bipolar stepper with 4 inputs showing two coils would be useful.

Something like this:
![bipolar-stepper-motor-wiring-labels](https://github.com/circuitdiagram/components/assets/151070291/ac204a26-be98-424e-9186-c35388d15b51)

As opposed to
![default](https://github.com/circuitdiagram/components/assets/151070291/0ca10cdf-e9b1-4cbe-84f0-f1a9dd24f2a5)

**Comment by biancaquig** [comment]
I agree

**Comment by moreirasavio** [comment]
I agree

**Comment by SamuelFisher** [comment]
This is now available:

https://www.circuit-diagram.org/components/8586a4fe-7420-4cae-870d-5f02975e3883

**Comment by moreirasavio** [comment]
thank you
