### ISSUE TITLE
Filters

### ISSUE THREAD

**Issue by taruncousik** [circuitdiagram/components#305]
Low Pass, Band Pass, Band Stop, High Pass. Useful to have it as a block instead of designing them

**Comment by MarioSanz** [comment]
Hi there @taruncousik, I made a component for that, maybe you want to give some feedback on it. This is the band-stop type, but I made it configurable for the other types you mentioned, plus an additional option for switched-capacitor type
![Frequency-filter](https://github.com/user-attachments/assets/6d5977e2-6597-4e32-9600-eb78f3e436bb)

@SamuelFisher Is there a pipeline to submit and review new components?

**Comment by SamuelFisher** [comment]
HI @MarioSanz, this looks great.

> Is there a pipeline to submit and review new components?

If you raise a PR in this repo I will prioritise reviewing it. Reviewing is quite time consuming, it will make it a lot easier if you can check things like this in advance before raising a PR:

1. Does it display correctly at different sizes/when resizing
2. Does it display correctly when placed vertically (not only horizontally)
3. Do the connection points (pins where other components and wires can connect to) align correctly, including for different sizes and vertical placement

**Comment by SamuelFisher** [comment]
Added in linked PR.
