### ISSUE TITLE
LCD-1602 screen

### ISSUE THREAD

**Issue by heidinv12** [circuitdiagram/components#31]
Hope this screenshot helps:

![image](https://user-images.githubusercontent.com/14826624/51802215-0df47a80-221e-11e9-84ca-35bbd0ac90b1.png)

**Comment by SamuelFisher** [comment]
The [HD44780 Display](https://www.circuit-diagram.org/components/1322b493-8fdf-4f5d-a8f0-40ce23b1eede) might be what you need for this.
