### ISSUE TITLE
RF Receiving Antenna request

### ISSUE THREAD

**Issue by HotAntenna** [circuitdiagram/components#39]
Trying to simulate an RF detector circuit.
Tried AC generator, will not simulate as an RF source

**Comment by SamuelFisher** [comment]
An antenna component has been added. However, it can't be simulated.

![image](https://user-images.githubusercontent.com/5303088/56569740-7cdd3780-65b1-11e9-85ea-3f2f6992a68e.png)

https://www.circuit-diagram.org/components/150eb28e-a9c3-47e7-9c9e-3fc38ef55b65
