### ISSUE TITLE
AC-DC, DC-AC and DC-DC converter request

### ISSUE THREAD

**Issue by EwanBeattie** [circuitdiagram/components#40]
Can you please make some converter components?

**Comment by Corsaka** [comment]
A DC-DC converter...?

**Comment by Corsaka** [comment]
As in, step-up and step-down transformers?

**Comment by EwanBeattie** [comment]
Yes essentially, but the symbol is very similar to the AC-DC converter. I though it would be easy to make one of these if the AC-DC converter was made

https://gallery.proficad.com/symbols/electrical-installations/production-of-electrical-energy/DC-DC-converter.html

**Comment by SamuelFisher** [comment]
This has been added in 8d823a5:

![image](https://user-images.githubusercontent.com/5303088/56585087-094d2180-65d5-11e9-8049-6d0564024d90.png)

https://www.circuit-diagram.org/components/237bdf11-0675-4de4-a324-3941e868ecf4
