### ISSUE TITLE
Lack of switches DPDT, DPST

### ISSUE THREAD

**Issue by ahmed240** [circuitdiagram/components#41]
It would be helpful to include DPDT and DPST switches
DPST
![Dual-On-Off-Switch-DPST-Circuit-Symbol](https://user-images.githubusercontent.com/1023265/57021217-e00f3f80-6c2b-11e9-8717-8e06ac769b2a.jpg)

DPDT
![DPDT-Circuit-Symbol](https://user-images.githubusercontent.com/1023265/57021218-e00f3f80-6c2b-11e9-8a5a-7952e4efc175.jpg)

**Comment by SamuelFisher** [comment]
These have been added in 7a3ab14:

![image](https://user-images.githubusercontent.com/5303088/62422023-93f8ee80-b6a3-11e9-8fe6-f143be1215e6.png)

https://www.circuit-diagram.org/components/27701dba-b023-43ad-9f88-b8a2dd0af1d1
