### ISSUE TITLE
Ohmmeter

### ISSUE THREAD

**Issue by saberline152** [circuitdiagram/components#43]
There is currently only a volt or ammeter, sometimes we may need a ohmmeter
![getfile](https://user-images.githubusercontent.com/47817124/57970285-c84fef00-797f-11e9-9707-360f331bc58a.png)

**Comment by SamuelFisher** [comment]
This has been added in e2ac69b.

![image](https://user-images.githubusercontent.com/5303088/58048168-0432b200-7b42-11e9-824a-edd5fdb0bb4e.png)
