### ISSUE TITLE
ESP32

### ISSUE THREAD

**Issue by AndrewDamz** [circuitdiagram/components#51]
It will be great to have this too

**Comment by Corsaka** [comment]
This seems like it'd be filled by using the "Integrated Circuit" or "Integrated Circuit 2" component, which is editable by simply clicking on it.

**Comment by SamuelFisher** [comment]
You can make this using one of the Integrated Circuit components. If you do that you can raise a PR to add the [YAML defintition](https://www.circuit-diagram.org/help/new-components) here if you'd like.
