### ISSUE TITLE
VSCode extension unable to find executable

### ISSUE THREAD

**Issue by Corsaka** [circuitdiagram/components#54]
Current path:
`{     "circuitDiagram.executablePath": "C:\Program Files\Circuit Diagram Custom Content\circuit-diagram-cli.exe" }`

![image](https://user-images.githubusercontent.com/23699128/62424709-7f7c1c80-b6ca-11e9-8136-033429b92ffd.png)

It's also been tried with forward slashes, two backward slashes, and two forward slashes.

I don't know what else could be the issue here.

**Comment by SamuelFisher** [comment]
Please could you try running the following in PowerShell to check there are no special characters in the path?

```ps
Test-Path "C:\Program Files\Circuit Diagram Custom Content\circuit-diagram-cli.exe"
```

**Comment by Corsaka** [comment]
![image](https://user-images.githubusercontent.com/23699128/62480606-33070e80-b7a8-11e9-9b65-233f1814c087.png)

**Comment by SamuelFisher** [comment]
Thanks. Setting that with two backward slashes should do the right thing, but it's odd that didn't work.

```
{ "circuitDiagram.executablePath": "C:\\Program Files\\Circuit Diagram Custom Content\\circuit-diagram-cli.exe" }
```

Are you running Windows 32 or 64-bit?

You can check using the following PowerShell command:

```
> gwmi win32_operatingsystem | select OSArchitecture

OSArchitecture
--------------
64-bit
```

**Comment by Corsaka** [comment]
64-bit. I'll try reinstalling the vsix and reconfiguring the settings.
