### ISSUE TITLE
Text instead of value for all / more components

### ISSUE THREAD

**Issue by JambonSama** [circuitdiagram/components#55]
Some components can display texts, but some can only display a value, or even nothing : 

- the resistor has so many cool fields : 
![image](https://user-images.githubusercontent.com/33868517/62425198-afcab780-b6d8-11e9-91cb-ddd98959bc08.png)
I can display the value or the text, and their is only one component but I can choose between all the way of representing a resistor (so, obviously the field 'IEC / US' and the field 'type' are awesome).

- the inductor is a little more tricky : 
![image](https://user-images.githubusercontent.com/33868517/62425377-67ac9480-b6da-11e9-94dd-3e93dc96b45d.png)
I would ideally like to have similar options of writing a value and a text, and displaying one or the other (or both ? maybe ?) and proposing the different ways of displaying an inductor (either the looping thing or the filled rectangle for example) would be really nice.

- and finally the motor : 
![image](https://user-images.githubusercontent.com/33868517/62425370-55caf180-b6da-11e9-9de1-32cc320d64a0.png)
Yeah, the image speaks for itself : the possibility to add text besides the component would be super awesome.

I'm writing this from a place of "I want to draw theoretical diagrams for papers and reports, and sometimes those need to be commented, but the values don't always matter depending on what you want to show".

**Comment by Corsaka** [comment]
There's a label "component". Use that.

**Comment by JambonSama** [comment]
Nice, thanks, I should have checked that before bothering you. 
But still, what if I want the value field of my component not to show, then ?
![image](https://user-images.githubusercontent.com/33868517/62452914-6bd7c100-b771-11e9-8396-e87cde2e8a88.png)

**Comment by SamuelFisher** [comment]
Hi @JambonSama, thanks for highlighting these issues and for the suggestion of more display styles for the inductor component.

For now I have added support for the inductor to display text instead of the inductance value:

![image](https://user-images.githubusercontent.com/5303088/62491390-a5d1b300-b7c3-11e9-8588-2b6406734d65.png)

For the motor it's probably best to use a label to add text.

Please let me know if there are any issues.

**Comment by JambonSama** [comment]
Thank you very much!
