### ISSUE TITLE
Add REV Expansion Hub

### ISSUE THREAD

**Issue by danielbrownmsm** [circuitdiagram/components#68]
For everyone who does FTC and robotics in general. I made one in the online web editor as a cdcom file, but it isn't letting me import the component, says it only takes cddx (I'm using strictly web version, on a chromebook)

**Comment by SamuelFisher** [comment]
Components cannot be imported into the web editor. In order to use custom components, the XML version needs to be added to this repository by raising a pull request.

Please see here for more information: https://componenteditor.com/help/finishing/
