### ISSUE TITLE
Generator

### ISSUE THREAD

**Issue by 15-ai** [circuitdiagram/components#69]
It would be very helpful to have a generator circuit symbol to use.

**Comment by SamuelFisher** [comment]
Hi, does this include the type you need?

![image](https://user-images.githubusercontent.com/5303088/72216218-4d42d680-3516-11ea-8008-99eed7e312ce.png)

**Comment by 15-ai** [comment]
Hi,
Thanks for your response, it does include the type of generator that I need.
Could you please tell me where I can find these to add on to the Circuit Diagram program,
since I’m new to the program and using it for the first time.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by SamuelFisher** [comment]
This has been added in 4ce4e6674d436fecf0b7832f611b2d70e3ae3878.

It will be available to use in the [Web Editor]() shortly (please allow a bit of time for it to appear) by using the _Add more components_ button:

![image](https://user-images.githubusercontent.com/5303088/72218579-1e3b5d80-3534-11ea-871f-a06e8b8a466c.png)

To use in Circuit Diagram Desktop, download the CDCOM file from [here](https://www.circuit-diagram.org/components/15c74cca-a629-47f8-8b11-67ca282523ad) and follow [these instructions](https://www.circuit-diagram.org/help/installing-components).

**Comment by 15-ai** [comment]
Thank you very much for the quick response as I needed the software for a school project which is due very soon.
And I’m sorry for bothering you with something which was already there but this is my first time using this program.

Kind regards,
15-ai

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________
