### ISSUE TITLE
BLDC motor three-phase

### ISSUE THREAD

**Issue by jurik555** [circuitdiagram/components#72]
Pls, include BLDC motor three-phase

`<?xml version="1.0" encoding="utf-8"?>
<component version="1.0" xmlns="http://schemas.circuit-diagram.org/circuitDiagramDocument/2012/component/xml">
  <declaration>
    <meta name="name" value="Motor BLDC" />
    <meta name="minsize" value="30" />
    <meta name="author" value="Circuit Diagram" />
    <meta name="additionalinformation" value="http://www.circuit-diagram.org/" />
    <meta name="guid" value="be9baf1f-61e9-4463-8a18-17b5e021087f" />
    <meta name="implementset" value="http://schemas.circuit-diagram.org/circuitDiagramDocument/2012/components/common" />
    <meta name="implementitem" value="motor" />
    <meta name="org.circuit-diagram.bundled" value="true" />
  </declaration>
  <connections>
    <group conditions="_Horizontal">
      <connection name="a" start="_Start" end="_Middle-13x" edge="Start" />
      <connection name="b" start="_Middle+13x" end="_End" edge="End" />
	  <connection name="c" start="_Middle+13y" end="_Middle+26y" edge="End" />
    </group>
    <group conditions="!_Horizontal">
      <connection name="a" start="_Start" end="_Middle-13y" edge="Start" />
      <connection name="b" start="_Middle+13y" end="_End" edge="End" />
	  <connection name="c" start="_Middle+13x" end="_Middle+26x" edge="End" />
    </group>
  </connections>
  <render>
    
    <group conditions="_Horizontal">
      <line start="_Start" end="_Middle-13x" />
      <line start="_Middle+13x" end="_End" />
	  <line start="_Middle+13y" end="_Middle+26y" />
    </group>
    <group conditions="!_Horizontal">
      <line start="_Start" end="_Middle-13y" />
      <line start="_Middle+13y" end="_End" />
<line start="_Middle+13x" end="_Middle+26x" />
    </group>
    <group>
      <ellipse x="_Middle" y="_Middle" radiusx="12" radiusy="12" />
      <text x="_Middle" y="_Middle" value="M" align="CentreCentre" size="large" />
    </group>
  </render>
</component>
	`

**Comment by SamuelFisher** [comment]
A three-phase motor has been added - please [see here for details](https://www.circuit-diagram.org/components/be9baf1f-61e9-4463-8a18-17b5e021087f).

![image](https://user-images.githubusercontent.com/5303088/73141011-30121a00-4077-11ea-9671-9833bed19752.png)
