### ISSUE TITLE
Electrolytic Capacitor

### ISSUE THREAD

**Issue by MoonRockSound** [circuitdiagram/components#73]
Would be really great to have the standard

—)|—

Electrolytic Capacitor shape

**Comment by SamuelFisher** [comment]
This has been added - please [see here for details](https://www.circuit-diagram.org/components/154b7831-58e6-4126-b582-8c1cc2bdeb13).

![image](https://user-images.githubusercontent.com/5303088/73140983-d578be00-4076-11ea-95d8-61e76ec85fa2.png)
