### ISSUE TITLE
[Request] Adder symbol

### ISSUE THREAD

**Issue by jafinn3** [circuitdiagram/components#77]
An adder component would be useful. Thank you!

**Comment by SamuelFisher** [comment]
Please could you include an example of what you had in mind for this?

**Comment by jafinn3** [comment]
Looks like @Corsaka got it, but somethign like this: 
![image](https://user-images.githubusercontent.com/36329192/75509814-e3dc3180-59b6-11ea-828b-63f4166bbdcb.png)

Thanks!
