### ISSUE TITLE
Subtext in component creation

### ISSUE THREAD

**Issue by Corsaka** [circuitdiagram/components#78]
Right now I'm trying to make a section of text that is a lot smaller than the rest in order to separate it clearly, using the `size` option. However, this doesn't seem to work, as this:
```xml
<text x="_Start-5" y="_Middle" align="CentreCentre" size="large" value="C" />
<text x="_Start+5" y="_Middle" align="CentreCentre" size="small" value="in" />
```
Turns out as this:
![image](https://user-images.githubusercontent.com/23699128/75486096-d10c3180-59a3-11ea-8a3a-e6723780b312.png)
Is this at all possible, or is there some other way to indicate subtext I'm unaware of?

**Comment by SamuelFisher** [comment]
You can create a single text element that itself contains multiple text runs. Each text run can be one of the following: _span_ (normal text), _sub_ (subscript) or _sup_ (superscript).

See here for an example:

https://github.com/circuitdiagram/components/blob/e84e7a6bc457a8fd1139e7aa43227a591c7438a8/ic/microcontroller/microcontroller.xml#L67-L72

![image](https://user-images.githubusercontent.com/5303088/75487196-e1251080-59a5-11ea-8666-f81893b5f1ce.png)

**Comment by Corsaka** [comment]
So the `size` modifier is unnecessary? I've tried both "small" and "medium" and nothing seems to change.

**Comment by SamuelFisher** [comment]
You don't need to use `size` to make the text smaller when using `sub`/`sup`. The only option for size is `size="large"`. If you don't specify it defaults to normal/medium size.
