### ISSUE TITLE
Flop with optional falling edge, no inverted output and reset only

### ISSUE THREAD

**Issue by Welgriv** [circuitdiagram/components#92]
I just would like to modify the existing flop to add some more properties option, from left to right and up to down :
(1) Existing flop with set/reset, (2) Existing flop without set reset, (3) Flop with falling edge clock, (4) Flop without invert output nor resets, (5) Flop with reset only. 

![flops](https://user-images.githubusercontent.com/22592156/92240229-8de3cb80-eebc-11ea-8200-c1f165ae069b.png)

**Comment by SamuelFisher** [comment]
These options have been added:

![image](https://user-images.githubusercontent.com/5303088/92284471-f1401e80-eef9-11ea-9546-704f28434f9d.png)
