### ISSUE TITLE
[REQUEST] Please Add IR SENSOR TO THIS

### ISSUE THREAD

**Issue by gptshubham595** [circuitdiagram/components#97]
![IR](https://user-images.githubusercontent.com/24877361/96351314-2a160a80-10d8-11eb-85f8-2eccda1aa1ad.png)

**Comment by apollograce** [comment]
Sometimes shown like so:
![image](https://user-images.githubusercontent.com/794172/97010187-13761600-1513-11eb-8975-c567e06e5e26.png)
