### ISSUE TITLE
Please add JK Flip flop or latch

### ISSUE THREAD

**Issue by AnuragZw** [circuitdiagram/components#99]
![images](https://user-images.githubusercontent.com/64973572/98035223-26a3b280-1e3e-11eb-87f6-a0121e1fd9ab.jpg)
https://www.google.com/url?sa=i&url=https%3A%2F%2Flearnabout-electronics.org%2FDigital%2Fdig54.php&psig=AOvVaw0JARmfQMdlKPmnzcR9Mi3C&ust=1604520363935000&source=images&cd=vfe&ved=0CAIQjRxqFwoTCMCOjbeW5-wCFQAAAAAdAAAAABAF

**Comment by SamuelFisher** [comment]
This has been added:

https://www.circuit-diagram.org/components/f283e85c-9cf6-4836-b00a-5183d7a3f3cb
